### ISSUE TITLE
serving docker部署，能相互ping通，curl报错

### ISSUE THREAD

**Issue by zhuiguang49** [secretflow/serving#132]
alice的serving.config
```
{
  "id": "test_service_id",
  "serverConf": {
    "featureMapping": {
      "v24": "x24",
      "v22": "x22",
      "v21": "x21",
      "v25": "x25",
      "v23": "x23"
    },
    "host": "0.0.0.0",
    "servicePort": "9010",
    "communicationPort": "9110",
    "metricsExposerPort": 10306,
    "brpcBuiltinServicePort": 10307
  },
  "modelConf": {
    "modelId": "glm-test-1",
    "basePath": "/tmp/alice",
    "sourcePath": "examples/alice/glm-test.tar.gz",
    "sourceSha256": "c6308af488bcd6c54a48a145af17aa209dec463b5cb44d83c6b58195818c10a0",
    "sourceType": "ST_FILE"
  },
  "clusterConf": {
    "selfId": "alice",
    "parties": [
      {
        "id": "alice",
        "address": "alice-serving:9110"
      },
      {
        "id": "bob",
        "address": "bob-serving:9111"
      }
    ],
    "channelDesc": {
      "protocol": "http"
    }
  },
  "featureSourceConf": {
    "mockOpts": {}
  }
}
```

bob的serving.config
```
{
  "id": "test_service_id",
  "serverConf": {
    "featureMapping": {
      "v6": "x6",
      "v7": "x7",
      "v8": "x8",
      "v9": "x9",
      "v10": "x10"
    },
    "host": "0.0.0.0",
    "servicePort": "9011",
    "communicationPort": "9111",
    "metricsExposerPort": 10308,
    "brpcBuiltinServicePort": 10309
  },
  "modelConf": {
    "modelId": "glm-test-1",
    "basePath": "/tmp/bob",
    "sourcePath": "examples/bob/glm-test.tar.gz",
    "sourceSha256": "d45d34feae42d663875569c206ac20263480300a40e34deda4037e01aeb9b2f8",
    "sourceType": "ST_FILE"
  },
  "clusterConf": {
    "selfId": "bob",
    "parties": [
      {
        "id": "alice",
        "address": "alice-serving:9110"
      },
      {
        "id": "bob",
        "address": "bob-serving:9111"
      }
    ],
    "channel_desc": {
      "protocol": "http"
    }
  },
  "featureSourceConf": {
    "mockOpts": {}
  }
}
```

alice的docker-compose.yaml
```
version: "3.8"
services:
  serving:
    cap_add:
      - NET_ADMIN
    command:
      - /root/sf_serving/secretflow_serving
      - --serving_config_file=/root/sf_serving/conf/serving.config
      - --logging_config_file=/root/sf_serving/conf/logging.config
      - --trace_config_file=/root/sf_serving/conf/trace.config
    restart: always
    image: secretflow/serving-anolis8:latest
    container_name: alice-serving
    networks:
      - sf-network
    ports:
      - 4590:9010  # 服务端口
      - 9110:9110  # 通信端口
      - 10306:10306  # metrics端口
      - 10307:10307  # brpc端口
    volumes:
      - ./serving.config:/root/sf_serving/conf/serving.config
      - ./logging.config:/root/sf_serving/conf/logging.config
      - ./trace.config:/root/sf_serving/conf/trace.config
      - ./glm-test.tar.gz:/root/glm-test.tar.gz

networks:
  sf-network:
    external: true
```

bob的docker-compose.yaml
```
version: "3.8"
services:
  serving:
    cap_add:
      - NET_ADMIN
    command:
      - /root/sf_serving/secretflow_serving
      - --serving_config_file=/root/sf_serving/conf/serving.config
      - --logging_config_file=/root/sf_serving/conf/logging.config
      - --trace_config_file=/root/sf_serving/conf/trace.config
    restart: always
    image: secretflow/serving-anolis8:latest
    container_name: bob-serving
    networks:
      - sf-network
    ports:
      - 4591:9011  # 服务端口
      - 9111:9111  # 通信端口
      - 10308:10308  # metrics端口
      - 10309:10309  # brpc端口
    volumes:
      - ./serving.config:/root/sf_serving/conf/serving.config
      - ./logging.config:/root/sf_serving/conf/logging.config
      - ./trace.config:/root/sf_serving/conf/trace.config
      - ./glm-test.tar.gz:/root/glm-test.tar.gz

networks:
  sf-network:
    external: true
```

两个容器均已能正常运行，但是两个节点似乎没法相互连接，curl也报错connected failed

报错如下：

![Uploading 微信图片_20241216183910.png…]()
